BUSINESS STATISTICS

In [1]:
import statistics as st

li=[1,2,3,3,3,2,4]

st.mean(li)

2.5714285714285716

In [2]:
import statistics as st

li=[10,20,30,40,50]
st.median(li)


30

In [3]:
import statistics as st
li=[1,4,4,6,8,9,1,6,7]
st.mode(li)

1

Numpy filter

In [2]:
import numpy as np
arr=np.array([10,30,40,50,100,90])
b=[True,False,True,False,True,False]
newarr=arr[b]
print(newarr)

[ 10  40 100]


In [5]:
import numpy as np
arr=np.array([1,3,5,6,7,8,10])
result=filter(lambda x: x % 2 !=0,arr)
print(list(result))

[1, 3, 5, 7]


In [7]:
import numpy as np
arr=np.array([1,3,5,6,2,8,10])
result=filter(lambda x : x %2==0,arr)
print(list(result))

[6, 2, 8, 10]


Concatenation

In [11]:
a=np.arange(6).reshape(2,3)
print("A:",a)

b=np.arange(7,13).reshape(2,3)
print("B:",b)

con=np.concatenate((a,b))
print("CON:",con)

d=np.arange(14.28).reshape(2,3)
print("D:",d)

mat=np.concatenate((con,d))
print("Mat:",mat)

A: [[0 1 2]
 [3 4 5]]
B: [[ 7  8  9]
 [10 11 12]]
CON: [[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]


ValueError: cannot reshape array of size 15 into shape (2,3)

In [13]:
mat=np.dstack((a,b))
print(mat[1,1,1])
print(mat)

11
[[[ 0  7]
  [ 1  8]
  [ 2  9]]

 [[ 3 10]
  [ 4 11]
  [ 5 12]]]


In [14]:
v_stack=np.vstack((a,b,con))        #vertical stack
v_stack

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
v_stack=np.vstack((a,b))        #vertical stack
v_stack

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
h_stack=np.hstack((a,b))                #horizontal stack
h_stack

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [18]:
d_stack=np.dstack((a,b))
d_stack

array([[[ 0,  7],
        [ 1,  8],
        [ 2,  9]],

       [[ 3, 10],
        [ 4, 11],
        [ 5, 12]]])

In [19]:
mat1=np.concatenate((a,b),axis=1)
print(mat1)

[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


In [22]:
a=np.arange(6).reshape(2,3)
print("A:",a)

b=np.arange(7,13).reshape(2,3)
print("B:",b)

stack_mat=np.stack((a,b),axis=-1)
print("Stack:",stack_mat)

A: [[0 1 2]
 [3 4 5]]
B: [[ 7  8  9]
 [10 11 12]]
Stack: [[[ 0  7]
  [ 1  8]
  [ 2  9]]

 [[ 3 10]
  [ 4 11]
  [ 5 12]]]
