Importing 

In [1]:
import numpy as np
print(np.__version__)

1.24.1


ZERO Dimensional array

In [6]:
import numpy as np

arr=np.array(46)
print(arr)

46


1D Array

In [7]:
import numpy as np

a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


2D array

In [8]:
arr=np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


3D array

In [9]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


All Dimensions

In [10]:
print(np.array(10))                                         #0D
print(np.array([1,2]))                                       #1D
print(np.array([[1,2],[3,4]]))                               #2D
print(np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]))       #3D

10
[1 2]
[[1 2]
 [3 4]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [17]:
import numpy as np
arr=np.array([1,2,3,,4,5,6,7,8,,9,10],ndmin(4))
print(arr.ndim)

SyntaxError: invalid syntax (2405670413.py, line 2)

#NDMIN5

In [3]:
import numpy as np
print(np.array([1,2,3,4,5,6,7,8,9,10],ndmin=2))


[[ 1  2  3  4  5  6  7  8  9 10]]


In [7]:
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
(2, 5)


In [4]:
import numpy as np
arr=np.arange(10,21)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20]


Sorating Arrays

In [5]:
import numpy as np
arr=np.array([2,4,3,1,5,6,9,8])
sorted_array=np.sort(arr)
print(sorted_array)

[1 2 3 4 5 6 8 9]


In [7]:
import numpy as np
arr1=np.array(["h","a","c","d","f","e"])
sortedarray=np.sort(arr1)
print(sortedarray)

['a' 'c' 'd' 'e' 'f' 'h']


In [8]:
import numpy as np
arr1=np.array(["huli","supi","harish","aruna","manju","nagarja"])
sortedarray=np.sort(arr1)
print(sortedarray)

['aruna' 'harish' 'huli' 'manju' 'nagarja' 'supi']


In [1]:
import numpy as np
arr=np.array([50,20,300,400,500,600])
print(arr[3:5])

[400 500]


In [10]:
mat=np.array([[10,20,30,40,50],[30,40,20,70,80]])
print(mat)
print(mat[1,2])

[[10 20 30 40 50]
 [30 40 20 70 80]]
20


3D array matrix

In [14]:
mat=np.array([[[10,20,30],[90,80,70]],[[50,60,100],[71,72,73]]])
print(mat)
print("value:",mat[1,1,0])

[[[ 10  20  30]
  [ 90  80  70]]

 [[ 50  60 100]
  [ 71  72  73]]]
value: 71


In [15]:
arr=np.array([1,2,3,4,5,6])
print(arr[1:6:2])

[2 4 6]


In [16]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,1:4])

[6 7 8]


In [18]:
import numpy as np
arr=np.array([2,50,40,60,70,40])
val=np.where(arr==40)
print(val)

(array([2, 5], dtype=int64),)


In [19]:
arr=np.array([1,2,3,4,5])

val=np.where(arr%2==0)
print(val)

(array([1, 3], dtype=int64),)


Searchsorted

In [20]:
import numpy as np
arr=np.array([6,7,9,19])
x=np.searchsorted(arr,8)
print(x)

2


In [21]:
np.searchsorted([1,2,3,4,5],3)

2

In [22]:
np.searchsorted([1,2,3,4,5],3,side='right')

3

In [23]:
np.searchsorted([1,2,3,4,5],[-10,10,2,3])

array([0, 5, 1, 2], dtype=int64)

Reshaping an array:Reshape()

In [24]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
rs=arr.reshape(4,3)
rs

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
arr=np.array([[1,2],[3,4],[5,6]])
print(arr.reshape(-1))

[1 2 3 4 5 6]


In [28]:
arr=np.array([[1,2],[3,4]])
print(arr.reshape(-1))

[1 2 3 4]
