#1)checking nmpy versio

In [1]:
import numpy as np
print(np.version)

<module 'numpy.version' from 'c:\\Users\\azt\\.conda\\envs\\env1\\Lib\\site-packages\\numpy\\version.py'>


In [2]:
#2)ZERO Dimension array

import numpy as np
arr=np.array(42)
print(arr)

42


In [7]:
#2)1 Dimensional array

import numpy as np
arr=np.array([1,2,3])
print (arr)

[1 2 3]


In [8]:
#3)2 Dimensional array

import numpy as np
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [2]:
#4) 3 Dimensional array

import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [3]:
#5) Create array of 5 Dimensional array

import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [4]:
#6)How to check dimension (Using ndim)

a=np.array(42)
b=np.array([1,2,3,4,5])
print(a.ndim)
print(b.ndim)

0
1


In [10]:
#7) Find the shape the array

import numpy as np
arr1=np.array([1,3,5,7])
print(arr1.shape)

(4,)


In [11]:
np.zeros(2)

array([0., 0.])

In [12]:
np.ones(2)

array([1., 1.])

In [13]:
np.arange(4)

array([0, 1, 2, 3])

In [14]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [2]:
#8 Sorting an element is simple with np.sort()

import numpy as np
arr=np.array([2,1,5,3,7,4,6,8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
#9)Sorting alphabtical data

import numpy as np
arr=np.array(['mango','bananan','graphs','orange','cheerry'])
print(np.sort(arr))

['bananan' 'cheerry' 'graphs' 'mango' 'orange']


In [4]:
#10)Sorting 2D array

import numpy as np
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [5]:
#11)Access array elements

import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [6]:
data=np.array([1,2,3])
data[1]

2

In [7]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd elment on 1st row:',arr[0,1])

2nd elment on 1st row: 2


In [8]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [9]:
import numpy as np
arr=np.array([[1,2,3,4,5,],[6,7,8,9,10]])
print('last element from 2nd dimension:',arr[1,-1])

last element from 2nd dimension: 10


In [10]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [11]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [14]:
#WHERE()

import numpy as np
arr=np.array([1,2,3,40,5,40,40])
x=np.where(arr==40)
print(x)

(array([3, 5, 6], dtype=int64),)


In [15]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%4==0)
print(x)

(array([3, 7], dtype=int64),)


In [13]:
#Searchsorted() programs

import numpy as np
arr=np.array([6,7,9,19])
x=np.searchsorted(arr,8)
print(x)

2


In [16]:
np.searchsorted([1,2,3,4,5],3)

2

In [18]:
np.searchsorted([1,2,3,4,5],[-10,10,2,3])

array([0, 5, 1, 2], dtype=int64)

In [19]:
np.searchsorted([1,2,3,4,5],3,side='right')

3

In [20]:
#Reshaping array

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
#Convert the array into 1D array:(-1)

import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [23]:
# Filtering array

import numpy as np
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[41 43]


In [24]:
seq=[0,1,2,3,5,8,13]
result=filter(lambda x:x%2!=0,seq)
print(list(result))
result=filter(lambda x:x%2==0,seq)
print(list(result))

[1, 3, 5, 13]
[0, 2, 8]


Joinig arry

In [26]:
# 1)Concatenate()

a=np.arange(6).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [27]:
#2)
b=np.arange(7,13).reshape(2,3)
print(b)

[[ 7  8  9]
 [10 11 12]]


In [28]:
np.concatenate((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
#VStACK

np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
np.hstack((a,b))

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [31]:
np.dstack((a,b))

array([[[ 0,  7],
        [ 1,  8],
        [ 2,  9]],

       [[ 3, 10],
        [ 4, 11],
        [ 5, 12]]])

In [4]:
import pandas as pd
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,100])
s=pd.Series(a)
s

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int32